language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script:
- python setup.py test
cache: pip
deploy:
  provider: pypi
  user: rapiddevsolutions
  password:
    secure: GtEMlQoHTcwTd5gh9iTS9v36bzeOOBW2+Rw83JJM5sVQ1QEaf63+cR5Mug2wsBLEy5iUtM4RQAWsXCJrkBFwuOqoSyn+Loib2o670kpovkxvf9mvuJUZLoOjrZrn62Z+9FPBBBnwA9VhCPADR/AV9V0t/U5MQaqtaay604c6rxqajtb/Eyn7exIkezdP4EZJVwzmt1YA7Nyovvoo/rSEjFmgfPyxT2dxGgb3guTdimtQ9EpRe++s/a5oJBvW24K988RTXvG9VjIPEkmAtAmkdpqjtnOU7NcAH0BOUcfT3zwx3k2+ZREUja3HdhVhTw92FLLd5bvj5lugtSab49YQIFka3OvU+gq9dLOFHxW9m6wRNT6YDslrEWc8/tS2z2nz1NgNcMzlBXikXw1+nO9z0ao9QWwrbM+Co5dgu5dbw/3Oniz2gqAnnuv4KRnpIXg2hW9kwARJr9iRBo4I2AKAEmnRYd1RGtjykKdDhpkCjB5j3ETF2XX2eomnBTYFg4CBSgyn2hXpe+eXtXJsA2eV5PvByU0AxQcF4u2PE+QaD3LgXxvD+Wzrlvr7uV7sqh99WNRxRMGLaYfEYvhtttk9sOjywAiWBW+t+q2jp58d1puYwH7+VUQoFCnZ3TvoGFZ9KWPp6OkZMdZGkM7gCDBT61m4KmcGl6LHoOhm/8GOg0c=
  on:
    tags: true
